
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int DIVIDE = 14;
  public static final int GREAT = 16;
  public static final int INSTR = 4;
  public static final int INTEGER = 36;
  public static final int LPAREN = 32;
  public static final int SEMI = 21;
  public static final int INT = 8;
  public static final int LESS = 17;
  public static final int MINUS = 26;
  public static final int BAR = 22;
  public static final int RPAREN = 33;
  public static final int GEQ = 18;
  public static final int NOTENAME = 34;
  public static final int PLUS = 25;
  public static final int IF = 11;
  public static final int BPM = 3;
  public static final int DOT = 30;
  public static final int TEMPO = 7;
  public static final int EOF = 0;
  public static final int VELOC = 6;
  public static final int EQUAL = 23;
  public static final int error = 1;
  public static final int SETOCT = 10;
  public static final int LCURLY = 28;
  public static final int PERCENT = 31;
  public static final int CUROC = 5;
  public static final int NEQ = 20;
  public static final int RCURLY = 29;
  public static final int SEGMENT = 9;
  public static final int TIMES = 13;
  public static final int MUSIC = 2;
  public static final int COLON = 24;
  public static final int ELSE = 12;
  public static final int SHARP = 27;
  public static final int EQUIV = 15;
  public static final int LEQ = 19;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MUSIC",
  "BPM",
  "INSTR",
  "CUROC",
  "VELOC",
  "TEMPO",
  "INT",
  "SEGMENT",
  "SETOCT",
  "IF",
  "ELSE",
  "TIMES",
  "DIVIDE",
  "EQUIV",
  "GREAT",
  "LESS",
  "GEQ",
  "LEQ",
  "NEQ",
  "SEMI",
  "BAR",
  "EQUAL",
  "COLON",
  "PLUS",
  "MINUS",
  "SHARP",
  "LCURLY",
  "RCURLY",
  "DOT",
  "PERCENT",
  "LPAREN",
  "RPAREN",
  "NOTENAME",
  "IDENTIFIER",
  "INTEGER"
  };
}

